import {useId,type FormHTMLAttributes,type HTMLAttributes,type LabelHTMLAttributes,type ReactNode} from 'react';import {Icon} from '../Icon';import {cx} from '../utils'
export type FieldState='default'|'success'|'warning'|'error'
export function FormLabel({required=false,optional=false,children,className,...props}:LabelHTMLAttributes<HTMLLabelElement>&{required?:boolean;optional?:boolean}){return <label className={cx('form-label',className)} {...props}>{children}{required&&<span className="form-required" aria-hidden="true">*</span>}{optional&&<span className="form-optional">اختیاری</span>}</label>}
export const FormHint=({children,id,className}:{children:ReactNode;id?:string;className?:string})=><span id={id} className={cx('form-message form-hint',className)}>{children}</span>
export const FormError=({children,id,className}:{children:ReactNode;id?:string;className?:string})=><span id={id} className={cx('form-message form-error',className)} role="alert"><Icon name="alert" size="xs"/>{children}</span>
export const FormSuccess=({children,id,className}:{children:ReactNode;id?:string;className?:string})=><span id={id} className={cx('form-message form-success',className)}><Icon name="check-square" size="xs"/>{children}</span>
export interface FormFieldProps{label?:ReactNode;htmlFor?:string;required?:boolean;optional?:boolean;hint?:ReactNode;error?:ReactNode;success?:ReactNode;warning?:ReactNode;children:ReactNode;className?:string}
export function FormField({label,htmlFor,required,optional,hint,error,success,warning,children,className}:FormFieldProps){const generated=useId();const id=htmlFor??generated;return <div className={cx('form-field',error&&'has-error',success&&'has-success',warning&&'has-warning',className)}>{label&&<FormLabel htmlFor={id} required={required} optional={optional}>{label}</FormLabel>}{children}{error?<FormError id={`${id}-error`}>{error}</FormError>:success?<FormSuccess id={`${id}-success`}>{success}</FormSuccess>:warning?<span id={`${id}-warning`} className="form-message form-warning"><Icon name="alert" size="xs"/>{warning}</span>:hint?<FormHint id={`${id}-hint`}>{hint}</FormHint>:null}</div>}
export const Form=({className,...props}:FormHTMLAttributes<HTMLFormElement>)=><form className={cx('ui-form',className)} {...props}/>
export const FormGroup=({className,...props}:HTMLAttributes<HTMLDivElement>)=><div className={cx('form-group',className)} {...props}/>
export const FormRow=({className,...props}:HTMLAttributes<HTMLDivElement>)=><div className={cx('form-row',className)} {...props}/>
export function FormSection({title,description,children,className,...props}:HTMLAttributes<HTMLElement>&{title?:ReactNode;description?:ReactNode}){return <section className={cx('form-section-block',className)} {...props}>{(title||description)&&<header><h2>{title}</h2>{description&&<p>{description}</p>}</header>}<div className="form-section-block__content">{children}</div></section>}
export const FormActions=({className,...props}:HTMLAttributes<HTMLDivElement>)=><div className={cx('form-actions',className)} {...props}/>
