import {forwardRef,useState,type FocusEvent,type KeyboardEvent,type WheelEvent} from 'react';import {Icon} from '../Icon';import {TextField,type TextFieldProps} from './TextField'
export interface PasswordFieldProps extends Omit<TextFieldProps,'type'|'endIcon'>{showStrength?:boolean;strength?:0|1|2|3|4}
export const PasswordField=forwardRef<HTMLInputElement,PasswordFieldProps>(function PasswordField({showStrength=false,strength=0,onKeyUp,onKeyDown,warning,...props},ref){const [visible,setVisible]=useState(false);const [capsLock,setCapsLock]=useState(false);const check=(event:KeyboardEvent<HTMLInputElement>)=>setCapsLock(event.getModifierState('CapsLock'));return <div className="password-control"><TextField {...props} ref={ref} type={visible?'text':'password'} autoComplete="current-password" endIcon={<button type="button" className="embedded-action" aria-label={visible?'پنهان کردن رمز عبور':'نمایش رمز عبور'} aria-pressed={visible} onClick={()=>setVisible((value)=>!value)}><Icon name={visible?'eye-off':'eye'} size="sm"/></button>} warning={capsLock?'کلید Caps Lock روشن است.':warning} onKeyUp={(event)=>{check(event);onKeyUp?.(event)}} onKeyDown={(event)=>{check(event);onKeyDown?.(event)}}/>{showStrength&&<div className="password-strength" role="meter" aria-valuemin={0} aria-valuemax={4} aria-valuenow={strength} aria-label="قدرت رمز عبور">{[1,2,3,4].map((level)=><span key={level} className={level<=strength?'is-active':undefined}/>)}</div>}</div>})
export interface NumberFieldProps extends Omit<TextFieldProps,'type'|'inputMode'>{preventWheel?:boolean;integer?:boolean}
export const NumberField=forwardRef<HTMLInputElement,NumberFieldProps>(function NumberField({preventWheel=true,integer=false,step,onWheel,...props},ref){const wheel=(event:WheelEvent<HTMLInputElement>)=>{if(preventWheel)event.currentTarget.blur();onWheel?.(event)};return <TextField ref={ref} type="number" inputMode={integer?'numeric':'decimal'} step={step??(integer?1:'any')} onWheel={wheel} {...props}/>})
export interface EmailFieldProps extends Omit<TextFieldProps,'type'|'inputMode'>{validateOnBlur?:boolean}
export const EmailField=forwardRef<HTMLInputElement,EmailFieldProps>(function EmailField({validateOnBlur=true,error,onBlur,...props},ref){const [internalError,setInternalError]=useState<string>();const blur=(event:FocusEvent<HTMLInputElement>)=>{if(validateOnBlur)setInternalError(event.currentTarget.value&&event.currentTarget.validity.typeMismatch?'نشانی ایمیل معتبر نیست.':undefined);onBlur?.(event)};return <TextField ref={ref} type="email" inputMode="email" autoComplete="email" error={error??internalError} onBlur={blur} {...props}/>})
export interface PhoneFieldProps extends Omit<TextFieldProps,'type'|'inputMode'>{countryCode?:string;pattern?:string}
export const PhoneField=forwardRef<HTMLInputElement,PhoneFieldProps>(function PhoneField({countryCode,pattern='[+۰-۹0-9\\s-]{7,20}',...props},ref){return <TextField ref={ref} type="tel" inputMode="tel" autoComplete="tel" prefix={countryCode} pattern={pattern} {...props}/>})
export interface SearchFieldProps extends Omit<TextFieldProps,'type'|'startIcon'|'clearable'>{onClear?():void;shortcut?:string}
export const SearchField=forwardRef<HTMLInputElement,SearchFieldProps>(function SearchField({onClear,shortcut,...props},ref){return <TextField ref={ref} type="search" startIcon={<Icon name="search" size="sm"/>} clearable onClear={onClear} suffix={shortcut?<kbd>{shortcut}</kbd>:undefined} {...props}/>})
