import { AuthorizationError } from '../../../core/errors'
import type { AuthorizedPrincipal } from '../../../security'
import type { AnalyticsService } from '../analytics'
import type { DashboardAlert, DashboardData, DashboardFilters, DashboardMetric } from '../types'

export class DashboardService {
  private readonly analytics: AnalyticsService
  constructor(analytics: AnalyticsService) { this.analytics = analytics }
  async getMainManagerDashboard(actor: AuthorizedPrincipal, filters: DashboardFilters = {}) { this.requireRole(actor, 'MAIN_MANAGER'); return this.build('نمای کلی سازمان', filters) }
  async getDepartmentDashboard(actor: AuthorizedPrincipal, departmentId: string, filters: DashboardFilters = {}) { this.requireRole(actor, 'DEPARTMENT_MANAGER'); if (!actor.departmentIds.includes(departmentId)) throw new AuthorizationError('DEPARTMENT_ACCESS_DENIED'); return this.build('داشبورد واحد', { ...filters, departmentId }) }
  async getEmployeeDashboard(actor: AuthorizedPrincipal, filters: DashboardFilters = {}) { this.requireRole(actor, 'EMPLOYEE'); return this.build('فضای کاری من', filters, actor.userId) }
  async getSecretaryDashboard(actor: AuthorizedPrincipal, filters: DashboardFilters = {}) { this.requireRole(actor, 'SECRETARY'); const data = await this.build('مدیریت جلسات', filters, actor.userId); return { ...data, metrics: data.metrics.filter((item) => item.title.includes('جلسه') || item.title.includes('گزارش')) } }
  private async build(title: string, filters: DashboardFilters, ownerId?: string): Promise<DashboardData> { const records = (await this.analytics.records(filters)).filter((item) => !ownerId || item.ownerId === ownerId); const tasks = await summarizeRecords(records, 'TASK'); const meetings = await summarizeRecords(records, 'MEETING'); const reports = await summarizeRecords(records, 'REPORT'); const metrics: DashboardMetric[] = [{ title: 'وظایف فعال', value: tasks.pending, status: 'STABLE' }, { title: 'وظایف تکمیل‌شده', value: tasks.completed, status: 'UP' }, { title: 'جلسات', value: meetings.total, status: 'STABLE' }, { title: 'گزارش‌های در انتظار', value: reports.pending, status: reports.pending ? 'DOWN' : 'STABLE' }]; const alerts: DashboardAlert[] = records.filter((item) => item.kind === 'TASK' && item.deadline && Date.parse(item.deadline) < Date.now() && item.status !== 'COMPLETED').map((item) => ({ id: `late-${item.id}`, title: 'وظیفه عقب‌افتاده', message: 'مهلت این وظیفه گذشته است.', type: 'DELAYED_TASK', entityId: item.id })); return { summary: { title, generatedAt: new Date().toISOString() }, metrics, charts: [{ id: 'work-status', title: 'وضعیت کار', type: 'BAR', data: [{ label: 'تکمیل', value: tasks.completed }, { label: 'در انتظار', value: tasks.pending }, { label: 'تاخیر', value: tasks.delayed }] }], recentActivities: records.slice(-5).reverse().map((item) => ({ id: item.id, title: `${item.kind} · ${item.status}`, date: item.createdAt })), alerts } }
  private requireRole(actor: AuthorizedPrincipal, role: AuthorizedPrincipal['roles'][number]) { if (!actor.roles.includes(role)) throw new AuthorizationError('DASHBOARD_ACCESS_DENIED') }
}
const summarizeRecords = async (records: readonly import('../types').AnalyticsRecord[], kind: import('../types').AnalyticsRecord['kind']) => { const items = records.filter((item) => item.kind === kind); return { total: items.length, completed: items.filter((item) => ['COMPLETED', 'APPROVED', 'FINAL'].includes(item.status)).length, pending: items.filter((item) => !['COMPLETED', 'APPROVED', 'FINAL'].includes(item.status)).length, delayed: items.filter((item) => item.deadline && Date.parse(item.deadline) < Date.now() && item.status !== 'COMPLETED').length } }
