import type { DepartmentReport, EmployeeReport } from '../../../domain/entities'
import { AppError } from '../../../errors'
import { authorize, isWithinScope, type AuthorizedPrincipal } from '../../../security'
import { Capabilities } from '../../../security/permissions'
import type { ActivityService } from '../../../services'
import type { UserDepartmentDataRepository } from '../../organization/repositories'
import type { DepartmentReportDataRepository, EmployeeReportDataRepository } from '../repositories'
import type { AccessibleReports, CreateDepartmentReportInput, CreateEmployeeReportInput } from '../types'

type RecipientResolver = (departmentId: string) => Promise<readonly string[]>
export class ReportService {
  private readonly employeeReports: EmployeeReportDataRepository
  private readonly departmentReports: DepartmentReportDataRepository
  private readonly memberships: UserDepartmentDataRepository
  private readonly activity: ActivityService
  private readonly managersFor: RecipientResolver
  private readonly mainManagers: () => Promise<readonly string[]>
  constructor(employeeReports: EmployeeReportDataRepository, departmentReports: DepartmentReportDataRepository, memberships: UserDepartmentDataRepository, activity: ActivityService, managersFor: RecipientResolver = async () => [], mainManagers: () => Promise<readonly string[]> = async () => []) { this.employeeReports = employeeReports; this.departmentReports = departmentReports; this.memberships = memberships; this.activity = activity; this.managersFor = managersFor; this.mainManagers = mainManagers }
  async createEmployeeReport(actor: AuthorizedPrincipal, input: CreateEmployeeReportInput) { authorize(actor, Capabilities.REPORT_CREATE); if (!actor.roles.includes('EMPLOYEE')) throw new AppError('PERMISSION_ERROR', 'این گزارش باید توسط کارمند ثبت شود.'); await this.assertMembership(actor.userId, input.departmentId); this.validateText(input.title, input.description); const item: EmployeeReport = { ...input, id: crypto.randomUUID(), employeeId: actor.userId, title: input.title.trim(), description: input.description.trim(), status: 'DRAFT', createdAt: new Date().toISOString() }; await this.employeeReports.create(item); await this.audit(actor, 'EMPLOYEE_REPORT_CREATED', item); return item }
  async updateDraftReport(actor: AuthorizedPrincipal, id: string, input: Pick<EmployeeReport, 'title' | 'description' | 'attachments'>) { const item = await this.requireEmployee(id); this.assertOwner(actor, item); if (item.status !== 'DRAFT' && item.status !== 'REQUIRES_CORRECTION') throw new AppError('VALIDATION_ERROR', 'فقط گزارش پیش‌نویس یا نیازمند اصلاح قابل ویرایش است.'); this.validateText(input.title, input.description); return this.employeeReports.update({ ...item, ...input, title: input.title.trim(), description: input.description.trim(), status: 'DRAFT' }) }
  async submitEmployeeReport(actor: AuthorizedPrincipal, id: string) { authorize(actor, Capabilities.REPORT_CREATE); const item = await this.requireEmployee(id); this.assertOwner(actor, item); if (item.status !== 'DRAFT') throw new AppError('VALIDATION_ERROR', 'فقط گزارش پیش‌نویس قابل ارسال است.'); const updated = await this.employeeReports.update({ ...item, status: 'SUBMITTED' }); await this.audit(actor, 'EMPLOYEE_REPORT_SUBMITTED', updated); await this.activity.notify(await this.managersFor(item.departmentId), { title: 'گزارش کارمند ارسال شد', message: item.title, priority: 'NORMAL' }); return updated }
  async reviewEmployeeReport(actor: AuthorizedPrincipal, id: string, approved: boolean, comment?: string) { authorize(actor, Capabilities.REPORT_REVIEW); this.assertDepartmentManager(actor); const item = await this.requireEmployee(id); this.assertScope(actor, item.departmentId); if (item.status !== 'SUBMITTED') throw new AppError('VALIDATION_ERROR', 'گزارش در انتظار بررسی نیست.'); if (!approved && !comment?.trim()) throw new AppError('VALIDATION_ERROR', 'توضیح اصلاح الزامی است.'); const updated = await this.employeeReports.update({ ...item, status: approved ? 'APPROVED' : 'REQUIRES_CORRECTION', managerComment: comment?.trim() }); await this.audit(actor, approved ? 'EMPLOYEE_REPORT_APPROVED' : 'EMPLOYEE_REPORT_CORRECTION_REQUESTED', updated); await this.activity.notify([item.employeeId], { title: approved ? 'گزارش تأیید شد' : 'اصلاح گزارش درخواست شد', message: comment?.trim() || item.title, priority: 'NORMAL' }); return updated }
  async createDepartmentReport(actor: AuthorizedPrincipal, input: CreateDepartmentReportInput) { authorize(actor, Capabilities.REPORT_CREATE); this.assertDepartmentManager(actor); this.assertScope(actor, input.departmentId); if (!input.period.trim() || !input.summary.trim()) throw new AppError('VALIDATION_ERROR', 'دوره و خلاصه گزارش الزامی است.'); const item: DepartmentReport = { ...input, id: crypto.randomUUID(), createdBy: actor.userId, period: input.period.trim(), summary: input.summary.trim(), status: 'DRAFT', createdAt: new Date().toISOString() }; await this.departmentReports.create(item); await this.audit(actor, 'DEPARTMENT_REPORT_CREATED', item); return item }
  async submitDepartmentReport(actor: AuthorizedPrincipal, id: string) { authorize(actor, Capabilities.REPORT_CREATE); this.assertDepartmentManager(actor); const item = await this.requireDepartment(id); this.assertScope(actor, item.departmentId); if (item.status !== 'DRAFT') throw new AppError('VALIDATION_ERROR', 'گزارش قبلاً ارسال شده است.'); const updated = await this.departmentReports.update({ ...item, status: 'SUBMITTED' }); await this.audit(actor, 'DEPARTMENT_REPORT_SUBMITTED', updated); await this.activity.notify(await this.mainManagers(), { title: 'گزارش واحد ارسال شد', message: item.summary, priority: 'HIGH' }); return updated }
  async getReports(actor: AuthorizedPrincipal): Promise<AccessibleReports> { authorize(actor, Capabilities.REPORT_VIEW); if (actor.roles.includes('MAIN_MANAGER')) return { employeeReports: [], departmentReports: (await this.departmentReports.findAll()).filter((item) => item.status === 'SUBMITTED') }; if (actor.roles.includes('DEPARTMENT_MANAGER')) { const employeeReports = (await Promise.all(actor.departmentIds.map((id) => this.employeeReports.findByDepartment(id)))).flat(); const departmentReports = (await Promise.all(actor.departmentIds.map((id) => this.departmentReports.findByDepartment(id)))).flat(); return { employeeReports, departmentReports } } return { employeeReports: await this.employeeReports.findByEmployee(actor.userId), departmentReports: [] } }
  private validateText(title: string, description: string) { if (!title.trim() || !description.trim()) throw new AppError('VALIDATION_ERROR', 'عنوان و شرح گزارش الزامی است.') }
  private async assertMembership(userId: string, departmentId: string) { if (!(await this.memberships.findByUser(userId)).some((item) => item.departmentId === departmentId)) throw new AppError('ACCESS_DENIED', 'امکان گزارش به واحدی که عضو آن نیستید وجود ندارد.') }
  private assertOwner(actor: AuthorizedPrincipal, report: EmployeeReport) { if (report.employeeId !== actor.userId) throw new AppError('ACCESS_DENIED', 'فقط مالک گزارش می‌تواند آن را تغییر دهد.') }
  private assertDepartmentManager(actor: AuthorizedPrincipal) { if (!actor.roles.includes('DEPARTMENT_MANAGER')) throw new AppError('PERMISSION_ERROR', 'این عملیات فقط برای مدیر واحد مجاز است.') }
  private assertScope(actor: AuthorizedPrincipal, departmentId: string) { if (!isWithinScope(actor, { departmentId })) throw new AppError('ACCESS_DENIED', 'گزارش خارج از واحد شماست.') }
  private async requireEmployee(id: string) { const item = await this.employeeReports.findById(id); if (!item) throw new AppError('NOT_FOUND', 'گزارش کارمند پیدا نشد.'); return item }
  private async requireDepartment(id: string) { const item = await this.departmentReports.findById(id); if (!item) throw new AppError('NOT_FOUND', 'گزارش واحد پیدا نشد.'); return item }
  private async audit(actor: AuthorizedPrincipal, action: string, after: unknown) { const item = after as { id: string }; await this.activity.record({ actorId: actor.userId, action, entityType: 'report', entityId: item.id, after }) }
}
