import type { Approval, Escalation, Reminder, WorkflowHistoryRecord, WorkflowInstance } from '../types'
export interface WorkflowRepository { createInstance(item: WorkflowInstance): Promise<WorkflowInstance>; updateInstance(item: WorkflowInstance): Promise<WorkflowInstance>; findInstance(id: string): Promise<WorkflowInstance | null>; findByEntity(entityType: string, entityId: string): Promise<WorkflowInstance | null>; addHistory(item: WorkflowHistoryRecord): Promise<WorkflowHistoryRecord>; findHistory(workflowId: string): Promise<readonly WorkflowHistoryRecord[]> }
export interface ApprovalRepository { create(item: Approval): Promise<Approval>; update(item: Approval): Promise<Approval>; findById(id: string): Promise<Approval | null>; findPending(approverId: string): Promise<readonly Approval[]> }
export interface ReminderRepository { save(item: Reminder): Promise<Reminder>; findDue(at: string): Promise<readonly Reminder[]> }
export interface EscalationRepository { create(item: Escalation): Promise<Escalation>; findByEntity(entityType: string, entityId: string): Promise<readonly Escalation[]> }
export class InMemoryWorkflowRepository implements WorkflowRepository { private instances = new Map<string, WorkflowInstance>(); private history: WorkflowHistoryRecord[] = []; async createInstance(item: WorkflowInstance) { this.instances.set(item.id, structuredClone(item)); return item } async updateInstance(item: WorkflowInstance) { this.instances.set(item.id, structuredClone(item)); return item } async findInstance(id: string) { return structuredClone(this.instances.get(id) ?? null) } async findByEntity(entityType: string, entityId: string) { return structuredClone([...this.instances.values()].find((item) => item.entityType === entityType && item.entityId === entityId) ?? null) } async addHistory(item: WorkflowHistoryRecord) { this.history.push(structuredClone(item)); return item } async findHistory(workflowId: string) { return this.history.filter((item) => item.workflowId === workflowId).map((item) => structuredClone(item)) } }
export class InMemoryApprovalRepository implements ApprovalRepository { private records = new Map<string, Approval>(); async create(item: Approval) { this.records.set(item.id, structuredClone(item)); return item } async update(item: Approval) { this.records.set(item.id, structuredClone(item)); return item } async findById(id: string) { return structuredClone(this.records.get(id) ?? null) } async findPending(approverId: string) { return [...this.records.values()].filter((item) => item.approverId === approverId && item.status === 'PENDING').map((item) => structuredClone(item)) } }
export class InMemoryReminderRepository implements ReminderRepository { private records = new Map<string, Reminder>(); async save(item: Reminder) { this.records.set(item.id, structuredClone(item)); return item } async findDue(at: string) { return [...this.records.values()].filter((item) => !item.sentAt && item.dueAt <= at).map((item) => structuredClone(item)) } }
export class InMemoryEscalationRepository implements EscalationRepository { private records: Escalation[] = []; async create(item: Escalation) { this.records.push(structuredClone(item)); return item } async findByEntity(entityType: string, entityId: string) { return this.records.filter((item) => item.entityType === entityType && item.entityId === entityId).map((item) => structuredClone(item)) } }
