import type {DataProvider} from '../../../core/data'
import type {StorageProvider} from '../../../core/storage'
import type {AuthorizedPrincipal,ResourceScope} from '../../../security'
import {FilePermissionService} from '../services/filePermissionService'
import type {FileAttachment,FileEntity} from '../types'

export interface FileRepository { create(item:FileAttachment):Promise<FileAttachment>;update(item:FileAttachment):Promise<FileAttachment>;delete(id:string):Promise<void>;findById(id:string):Promise<FileAttachment|null>;findByEntity(entityType:string,entityId:string):Promise<readonly FileAttachment[]>;findByUploader(userId:string):Promise<readonly FileAttachment[]> }
export class InMemoryFileRepository implements FileRepository { private records=new Map<string,FileAttachment>();async create(item:FileAttachment){this.records.set(item.id,structuredClone(item));return item}async update(item:FileAttachment){this.records.set(item.id,structuredClone(item));return item}async delete(id:string){this.records.delete(id)}async findById(id:string){return structuredClone(this.records.get(id)??null)}async findByEntity(entityType:string,entityId:string){return [...this.records.values()].filter((item)=>item.entityType===entityType&&item.entityId===entityId).map((item)=>structuredClone(item))}async findByUploader(userId:string){return [...this.records.values()].filter((item)=>item.uploadedBy===userId).map((item)=>structuredClone(item))}}
export class ProviderFileRepository { constructor(private readonly data:DataProvider,private readonly storage:StorageProvider,private readonly permissions=new FilePermissionService()){}async upload(file:FileEntity,blob:Blob){await this.storage.upload({key:file.storageKey,file:blob,contentType:file.mimeType});return this.data.create('files',file)}async download(actor:AuthorizedPrincipal,id:string,scope:ResourceScope){const file=await this.getFile(actor,id,scope);return this.storage.getUrl(file.storageKey)}async getFile(actor:AuthorizedPrincipal,id:string,scope:ResourceScope){const file=await this.data.get<FileEntity>('files',id);if(!file)throw new Error('FILE_NOT_FOUND');if(!this.permissions.canViewFile(actor,file,scope))throw new Error('FILE_ACCESS_DENIED');return file}async delete(actor:AuthorizedPrincipal,id:string,scope:ResourceScope){const file=await this.getFile(actor,id,scope);if(!this.permissions.canDeleteFile(actor,file,scope))throw new Error('FILE_DELETE_DENIED');await this.storage.delete(file.storageKey);await this.data.delete('files',id)}async listByEntity(actor:AuthorizedPrincipal,entityType:string,entityId:string,scope:ResourceScope){const items=await this.data.list<FileEntity>('files',{entityType,entityId});return items.filter((item)=>this.permissions.canViewFile(actor,item,scope))}async checkAccess(actor:AuthorizedPrincipal,id:string,scope:ResourceScope){await this.getFile(actor,id,scope);return true}}
