import { formatPersianDate } from '../../../core/utils'; import type { Evaluation, EvaluationCriteria, Feedback, PerformanceMetrics } from '../types'
export const ScoreCard = ({ title, score }: { title: string; score: number }) => <article className="card metric-card"><span>{title}</span><strong>{score.toLocaleString('fa-IR')}</strong><progress max="100" value={score}>{score}</progress></article>
export const PerformanceCard = ({ metrics }: { metrics: PerformanceMetrics }) => <div className="dashboard-grid"><ScoreCard title="عملکرد وظایف" score={metrics.taskScore} /><ScoreCard title="کیفیت گزارش" score={metrics.reportScore} /><ScoreCard title="نرخ تکمیل" score={metrics.completionRate} /><ScoreCard title="امتیاز کل" score={metrics.overallScore} /></div>
export const CriteriaTable = ({ criteria }: { criteria: readonly EvaluationCriteria[] }) => <table><thead><tr><th>معیار</th><th>امتیاز</th><th>وزن</th></tr></thead><tbody>{criteria.map((item) => <tr key={item.name}><td>{item.name}</td><td>{item.score}</td><td>{item.weight}٪</td></tr>)}</tbody></table>
export const FeedbackCard = ({ feedback }: { feedback: Feedback }) => <article className="card"><p>{feedback.message}</p><small>{feedback.fromUser} · {formatPersianDate(feedback.createdAt)}</small></article>
export const PerformanceChart = ({ evaluations }: { evaluations: readonly Evaluation[] }) => <div className="chart" role="img" aria-label="روند امتیاز ارزیابی">{evaluations.map((item) => <div key={item.id}><span>{item.period}</span><meter min="0" max="100" value={item.score}>{item.score}</meter><b>{item.score}</b></div>)}</div>
export const EvaluationTimeline = ({ evaluations }: { evaluations: readonly Evaluation[] }) => <ol className="timeline">{evaluations.map((item) => <li key={item.id}><strong>{item.period} · {item.score}</strong><span>{item.status}</span><time>{formatPersianDate(item.createdAt)}</time></li>)}</ol>
export const PerformanceTimeline = EvaluationTimeline
export const EvaluationForm = ({ onSubmit }: { onSubmit(): void }) => <form onSubmit={(event) => { event.preventDefault(); onSubmit() }}><button type="submit">ثبت ارزیابی</button></form>
