import type { Task, TaskReport } from '../../../domain/entities'
import { AppError } from '../../../errors'
import { authorize, isWithinScope, type AuthorizedPrincipal } from '../../../security'
import { Capabilities } from '../../../security/permissions'
import type { ActivityService } from '../../../services'
import type { DecisionDataRepository } from '../../meetings/repositories'
import type { UserDepartmentDataRepository } from '../../organization/repositories'
import type { TaskDataRepository, TaskReportDataRepository } from '../repositories'
import type { CreateTaskInput, SubmitTaskReportInput, TaskDashboardData } from '../types'
import { isTaskOverdue } from '../utils'

type DepartmentManagers = (departmentId: string) => Promise<readonly string[]>
export class TaskService {
  private readonly tasks: TaskDataRepository
  private readonly reports: TaskReportDataRepository
  private readonly decisions: DecisionDataRepository
  private readonly memberships: UserDepartmentDataRepository
  private readonly activity: ActivityService
  private readonly departmentManagers: DepartmentManagers
  constructor(tasks: TaskDataRepository, reports: TaskReportDataRepository, decisions: DecisionDataRepository, memberships: UserDepartmentDataRepository, activity: ActivityService, departmentManagers: DepartmentManagers = async () => []) { this.tasks = tasks; this.reports = reports; this.decisions = decisions; this.memberships = memberships; this.activity = activity; this.departmentManagers = departmentManagers }
  async createTask(actor: AuthorizedPrincipal, input: CreateTaskInput) {
    authorize(actor, Capabilities.TASK_CREATE, { departmentId: input.departmentId }); this.assertDepartmentManager(actor); this.validate(input)
    const decision = await this.decisions.findById(input.decisionId)
    if (!decision) throw new AppError('NOT_FOUND', 'تصمیم مبنا پیدا نشد.')
    if (decision.departmentId !== input.departmentId) throw new AppError('VALIDATION_ERROR', 'وظیفه باید در واحد تصمیم ایجاد شود.')
    await this.assertMember(input.assignedTo, input.departmentId)
    const item: Task = { ...input, id: crypto.randomUUID(), title: input.title.trim(), description: input.description.trim(), createdBy: actor.userId, status: 'PENDING', createdAt: new Date().toISOString() }
    await this.tasks.create(item); await this.audit(actor, 'TASK_CREATED', undefined, item); await this.activity.notify([item.assignedTo], { title: 'وظیفه جدید', message: item.title, priority: item.priority }); return item
  }
  async assignTask(actor: AuthorizedPrincipal, taskId: string, employeeId: string) { const updated = await this.changeAssignee(actor, taskId, employeeId, 'TASK_ASSIGNED'); await this.activity.notify([employeeId], { title: 'وظیفه به شما تخصیص یافت', message: updated.title, priority: updated.priority }); return updated }
  async reassignTask(actor: AuthorizedPrincipal, taskId: string, employeeId: string) { const updated = await this.changeAssignee(actor, taskId, employeeId, 'TASK_REASSIGNED'); await this.activity.notify([employeeId], { title: 'ارجاع مجدد وظیفه', message: updated.title, priority: updated.priority }); return updated }
  async updateTaskStatus(actor: AuthorizedPrincipal, taskId: string, status: 'IN_PROGRESS') { authorize(actor, Capabilities.TASK_UPDATE_SELF); const task = await this.require(taskId); this.assertOwner(actor, task); if (task.status !== 'PENDING') throw new AppError('VALIDATION_ERROR', 'فقط وظیفه در انتظار را می‌توان شروع کرد.'); const updated = await this.tasks.update({ ...task, status }); await this.audit(actor, 'TASK_STATUS_CHANGED', task, updated); await this.activity.notify(await this.departmentManagers(task.departmentId), { title: 'وضعیت وظیفه تغییر کرد', message: task.title, priority: 'NORMAL' }); return updated }
  async submitTaskReport(actor: AuthorizedPrincipal, taskId: string, input: SubmitTaskReportInput) { authorize(actor, Capabilities.REPORT_CREATE); const task = await this.require(taskId); this.assertOwner(actor, task); if (task.status !== 'IN_PROGRESS') throw new AppError('VALIDATION_ERROR', 'گزارش فقط برای وظیفه در حال انجام ثبت می‌شود.'); if (!input.description.trim()) throw new AppError('VALIDATION_ERROR', 'شرح گزارش الزامی است.'); const report: TaskReport = { id: crypto.randomUUID(), taskId, createdBy: actor.userId, description: input.description.trim(), attachments: input.attachments, createdAt: new Date().toISOString() }; await this.reports.create(report); const updated = await this.tasks.update({ ...task, status: 'WAITING_REVIEW' }); await this.audit(actor, 'TASK_REPORT_SUBMITTED', task, updated); await this.activity.notify(await this.departmentManagers(task.departmentId), { title: 'گزارش تکمیل وظیفه', message: task.title, priority: 'HIGH' }); return report }
  async reviewTask(actor: AuthorizedPrincipal, taskId: string, approved: boolean, reason?: string) { authorize(actor, Capabilities.TASK_REVIEW); this.assertDepartmentManager(actor); const task = await this.require(taskId); this.assertDepartmentScope(actor, task); if (task.status !== 'WAITING_REVIEW') throw new AppError('VALIDATION_ERROR', 'وظیفه در انتظار بررسی نیست.'); if (!approved && !reason?.trim()) throw new AppError('VALIDATION_ERROR', 'دلیل رد گزارش الزامی است.'); const updated = await this.tasks.update({ ...task, status: approved ? 'COMPLETED' : 'IN_PROGRESS' }); await this.audit(actor, approved ? 'TASK_COMPLETED' : 'TASK_REPORT_REJECTED', task, { ...updated, reviewReason: reason }); await this.activity.notify([task.assignedTo], { title: approved ? 'گزارش تأیید شد' : 'گزارش نیازمند اصلاح است', message: reason?.trim() || task.title, priority: 'HIGH' }); return updated }
  async cancelTask(actor: AuthorizedPrincipal, taskId: string, reason: string) { authorize(actor, Capabilities.TASK_REVIEW); this.assertDepartmentManager(actor); const task = await this.require(taskId); this.assertDepartmentScope(actor, task); if (!reason.trim()) throw new AppError('VALIDATION_ERROR', 'دلیل لغو الزامی است.'); if (task.status === 'COMPLETED' || task.status === 'CANCELLED') throw new AppError('VALIDATION_ERROR', 'وظیفه بسته‌شده قابل لغو نیست.'); const updated = await this.tasks.update({ ...task, status: 'CANCELLED' }); await this.audit(actor, 'TASK_CANCELLED', task, { ...updated, cancelReason: reason }); await this.activity.notify([task.assignedTo], { title: 'وظیفه لغو شد', message: reason, priority: 'HIGH' }); return updated }
  async getTasks(actor: AuthorizedPrincipal) { if (actor.roles.includes('MAIN_MANAGER')) { authorize(actor, Capabilities.TASK_VIEW); return this.tasks.findAll() } if (actor.roles.includes('DEPARTMENT_MANAGER')) { authorize(actor, Capabilities.TASK_VIEW); const groups = await Promise.all(actor.departmentIds.map((id) => this.tasks.findByDepartment(id))); return groups.flat() } authorize(actor, Capabilities.TASK_VIEW_SELF); return this.tasks.findByUser(actor.userId) }
  async getDashboardData(actor: AuthorizedPrincipal): Promise<TaskDashboardData> { const tasks = await this.getTasks(actor); return { active: tasks.filter((item) => item.status === 'PENDING' || item.status === 'IN_PROGRESS' || item.status === 'WAITING_REVIEW').length, completed: tasks.filter((item) => item.status === 'COMPLETED').length, overdue: tasks.filter((item) => isTaskOverdue(item)).length, departmentWorkload: tasks.reduce<Record<string, number>>((result, item) => ({ ...result, [item.departmentId]: (result[item.departmentId] ?? 0) + 1 }), {}) } }
  async sendDeadlineReminder(actor: AuthorizedPrincipal, taskId: string) { authorize(actor, Capabilities.TASK_REVIEW); this.assertDepartmentManager(actor); const task = await this.require(taskId); this.assertDepartmentScope(actor, task); if (task.status === 'COMPLETED' || task.status === 'CANCELLED') throw new AppError('VALIDATION_ERROR', 'وظیفه بسته‌شده نیاز به یادآوری ندارد.'); await this.activity.notify([task.assignedTo], { title: 'یادآوری مهلت وظیفه', message: task.title, priority: task.priority }) }
  private async changeAssignee(actor: AuthorizedPrincipal, taskId: string, employeeId: string, action: string) { authorize(actor, Capabilities.TASK_ASSIGN); this.assertDepartmentManager(actor); const task = await this.require(taskId); this.assertDepartmentScope(actor, task); await this.assertMember(employeeId, task.departmentId); const updated = await this.tasks.update({ ...task, assignedTo: employeeId }); await this.audit(actor, action, task, updated); return updated }
  private validate(input: CreateTaskInput) { if (!input.decisionId || !input.title.trim() || !input.description.trim() || !input.assignedTo || !input.deadline || Number.isNaN(Date.parse(input.deadline))) throw new AppError('VALIDATION_ERROR', 'اطلاعات وظیفه کامل و معتبر نیست.') }
  private async assertMember(userId: string, departmentId: string) { if (!(await this.memberships.findByUser(userId)).some((item) => item.departmentId === departmentId)) throw new AppError('VALIDATION_ERROR', 'مسئول وظیفه باید عضو همان واحد باشد.') }
  private assertDepartmentManager(actor: AuthorizedPrincipal) { if (!actor.roles.includes('DEPARTMENT_MANAGER')) throw new AppError('PERMISSION_ERROR', 'فقط مدیر واحد می‌تواند وظیفه عملیاتی را مدیریت کند.') }
  private assertDepartmentScope(actor: AuthorizedPrincipal, task: Task) { if (!isWithinScope(actor, { departmentId: task.departmentId })) throw new AppError('ACCESS_DENIED', 'وظیفه خارج از محدوده واحد شماست.') }
  private assertOwner(actor: AuthorizedPrincipal, task: Task) { if (task.assignedTo !== actor.userId) throw new AppError('ACCESS_DENIED', 'فقط مسئول وظیفه می‌تواند آن را به‌روزرسانی کند.') }
  private async require(id: string) { const task = await this.tasks.findById(id); if (!task) throw new AppError('NOT_FOUND', 'وظیفه پیدا نشد.'); return task }
  private async audit(actor: AuthorizedPrincipal, action: string, before: unknown, after: unknown) { const entity = after as Task; await this.activity.record({ actorId: actor.userId, action, entityType: 'task', entityId: entity.id, before, after }) }
}
