import type { RoleCode } from '../../../domain/enums'
import { Capabilities } from '../../../security/permissions'

export const roleCapabilities: Readonly<Record<RoleCode, readonly string[]>> = {
  MAIN_MANAGER: [Capabilities.ORGANIZATION_MANAGE, Capabilities.ORGANIZATION_VIEW, Capabilities.POSITION_MANAGE, Capabilities.USER_MANAGE, Capabilities.USER_VIEW, Capabilities.ROLE_MANAGE, Capabilities.CAPABILITY_MANAGE, Capabilities.MEETING_CREATE, Capabilities.MEETING_MANAGE, Capabilities.MEETING_VIEW, Capabilities.MINUTES_EDIT, Capabilities.MINUTES_FINALIZE, Capabilities.MINUTES_EDIT_FINAL, Capabilities.DECISION_CREATE, Capabilities.DECISION_VIEW, Capabilities.DECISION_EDIT_FINAL, Capabilities.TASK_VIEW, Capabilities.REPORT_VIEW, Capabilities.REPORT_REVIEW, Capabilities.REQUEST_CREATE, Capabilities.REQUEST_REVIEW, Capabilities.REQUEST_VIEW, Capabilities.EVENT_VIEW, Capabilities.NOTIFICATION_VIEW, Capabilities.FILE_MANAGE, Capabilities.AUDIT_VIEW, Capabilities.DASHBOARD_ORGANIZATION, Capabilities.WORKFLOW_MANAGE, Capabilities.APPROVAL_MANAGE, Capabilities.PERFORMANCE_ORGANIZATION],
  DEPARTMENT_MANAGER: [Capabilities.ORGANIZATION_VIEW, Capabilities.USER_VIEW, Capabilities.MEETING_VIEW, Capabilities.DECISION_CREATE, Capabilities.DECISION_EDIT, Capabilities.DECISION_VIEW, Capabilities.TASK_CREATE, Capabilities.TASK_ASSIGN, Capabilities.TASK_REVIEW, Capabilities.TASK_VIEW, Capabilities.REPORT_CREATE, Capabilities.REPORT_VIEW, Capabilities.REPORT_REVIEW, Capabilities.REQUEST_CREATE, Capabilities.REQUEST_REVIEW, Capabilities.REQUEST_VIEW, Capabilities.EVENT_VIEW, Capabilities.NOTIFICATION_VIEW, Capabilities.FILE_MANAGE, Capabilities.AUDIT_VIEW, Capabilities.DASHBOARD_DEPARTMENT, Capabilities.WORKFLOW_MANAGE, Capabilities.APPROVAL_MANAGE, Capabilities.PERFORMANCE_DEPARTMENT],
  SECRETARY: [Capabilities.MEETING_VIEW, Capabilities.MEETING_CREATE, Capabilities.MINUTES_CREATE, Capabilities.MINUTES_EDIT, Capabilities.MINUTES_FINALIZE, Capabilities.DECISION_CREATE, Capabilities.DECISION_EDIT, Capabilities.DECISION_VIEW, Capabilities.REPORT_CREATE, Capabilities.REPORT_VIEW, Capabilities.EVENT_VIEW, Capabilities.NOTIFICATION_VIEW, Capabilities.FILE_MANAGE, Capabilities.AUDIT_VIEW, Capabilities.DASHBOARD_MEETING],
  /* Employees are invited to meetings and see their own resolutions, so they
     need read-only meeting access — creating/managing stays with managers. */
  EMPLOYEE: [Capabilities.TASK_VIEW_SELF, Capabilities.TASK_UPDATE_SELF, Capabilities.MEETING_VIEW, Capabilities.DECISION_VIEW, Capabilities.REPORT_CREATE, Capabilities.REPORT_VIEW, Capabilities.REQUEST_CREATE, Capabilities.REQUEST_VIEW, Capabilities.EVENT_VIEW, Capabilities.NOTIFICATION_VIEW, Capabilities.FILE_MANAGE, Capabilities.WORKFLOW_SELF, Capabilities.DASHBOARD_SELF, Capabilities.PERFORMANCE_SELF],
}
