import { AuthorizationError, NotFoundError } from '../../../core/errors'
import type { AuthorizedPrincipal } from '../../../security'
import type { AuditService } from '../../audit'
import type { NotificationService } from '../../notifications'
import { assertTransition, canTransition } from '../engines'
import type { WorkflowRepository } from '../repositories'
import type { WorkflowInstance } from '../types'

export class WorkflowService {
  private readonly repository: WorkflowRepository; private readonly audit: AuditService; private readonly notifications: NotificationService
  constructor(repository: WorkflowRepository, audit: AuditService, notifications: NotificationService) { this.repository = repository; this.audit = audit; this.notifications = notifications }
  async createWorkflowInstance(actor: AuthorizedPrincipal, input: Pick<WorkflowInstance, 'entityType' | 'entityId' | 'currentStatus' | 'departmentId' | 'ownerId'>) { this.assertScope(actor, input.departmentId, input.ownerId); const existing = await this.repository.findByEntity(input.entityType, input.entityId); if (existing) return existing; const item: WorkflowInstance = { ...input, id: crypto.randomUUID(), createdBy: actor.userId, startedAt: new Date().toISOString() }; await this.repository.createInstance(item); await this.audit.logAction({ action: 'CREATE', event: 'WORKFLOW_CREATED', entityType: 'workflow', entityId: item.id, performedBy: actor.userId, description: 'گردش‌کار ایجاد شد.', newValue: item, metadata: { departmentId: item.departmentId, ownerId: item.ownerId } }); return item }
  async getWorkflowStatus(actor: AuthorizedPrincipal, id: string) { const item = await this.require(id); this.assertScope(actor, item.departmentId, item.ownerId); return item }
  validateTransition(entityType: string, from: string, to: string) { assertTransition(entityType, from, to); return true }
  async changeStatus(actor: AuthorizedPrincipal, id: string, toStatus: string, reason?: string, notifyUserIds: readonly string[] = []) { const current = await this.require(id); this.assertScope(actor, current.departmentId, current.ownerId); assertTransition(current.entityType, current.currentStatus, toStatus); const updated = { ...current, currentStatus: toStatus, completedAt: ['COMPLETED', 'APPROVED'].includes(toStatus) ? new Date().toISOString() : undefined }; await this.repository.updateInstance(updated); await this.repository.addHistory({ id: crypto.randomUUID(), workflowId: id, fromStatus: current.currentStatus, toStatus, changedBy: actor.userId, reason, createdAt: new Date().toISOString() }); await this.audit.logAction({ action: toStatus === 'APPROVED' || toStatus === 'COMPLETED' ? 'APPROVE' : toStatus === 'REJECTED' ? 'REJECT' : 'UPDATE', event: 'WORKFLOW_STATUS_CHANGED', entityType: current.entityType, entityId: current.entityId, performedBy: actor.userId, description: `وضعیت از ${current.currentStatus} به ${toStatus} تغییر کرد.`, oldValue: { status: current.currentStatus }, newValue: { status: toStatus }, metadata: { departmentId: current.departmentId, ownerId: current.ownerId, reason } }); if (notifyUserIds.length) await this.notifications.notifyUsers(notifyUserIds, { title: 'تغییر وضعیت', message: `${current.entityType}: ${toStatus}`, type: 'INFO', category: 'WORKFLOW', entityType: current.entityType, entityId: current.entityId, priority: 'NORMAL' }); return updated }
  async completeWorkflow(actor: AuthorizedPrincipal, id: string, notifyUserIds: readonly string[] = []) { return this.changeStatus(actor, id, 'COMPLETED', undefined, notifyUserIds) }
  async getHistory(actor: AuthorizedPrincipal, id: string) { await this.getWorkflowStatus(actor, id); return this.repository.findHistory(id) }
  canChange(entityType: string, from: string, to: string) { return canTransition(entityType, from, to) }
  private async require(id: string) { const item = await this.repository.findInstance(id); if (!item) throw new NotFoundError('WORKFLOW_NOT_FOUND'); return item }
  private assertScope(actor: AuthorizedPrincipal, departmentId?: string, ownerId?: string) { if (actor.roles.includes('MAIN_MANAGER')) return; if (actor.roles.includes('DEPARTMENT_MANAGER') && departmentId && actor.departmentIds.includes(departmentId)) return; if (ownerId === actor.userId) return; if (actor.roles.includes('SECRETARY')) throw new AuthorizationError('WORKFLOW_ACCESS_DENIED'); throw new AuthorizationError('WORKFLOW_ACCESS_DENIED') }
}
