import type { Request } from '../../../domain/entities'
import { AppError } from '../../../errors'
import { authorize, isWithinScope, type AuthorizedPrincipal } from '../../../security'
import { Capabilities } from '../../../security/permissions'
import type { ActivityService } from '../../../services'
import type { UserDepartmentDataRepository } from '../../organization/repositories'
import type { RequestDataRepository } from '../repositories'
import type { CreateRequestInput } from '../types'

type RecipientResolver = (departmentId: string) => Promise<readonly string[]>
export class RequestService {
  private readonly requests: RequestDataRepository
  private readonly memberships: UserDepartmentDataRepository
  private readonly activity: ActivityService
  private readonly managersFor: RecipientResolver
  private readonly mainManagers: () => Promise<readonly string[]>
  constructor(requests: RequestDataRepository, memberships: UserDepartmentDataRepository, activity: ActivityService, managersFor: RecipientResolver = async () => [], mainManagers: () => Promise<readonly string[]> = async () => []) { this.requests = requests; this.memberships = memberships; this.activity = activity; this.managersFor = managersFor; this.mainManagers = mainManagers }
  async createRequest(actor: AuthorizedPrincipal, input: CreateRequestInput) { authorize(actor, Capabilities.REQUEST_CREATE); this.validate(input); if (!await this.isMember(actor.userId, input.departmentId)) throw new AppError('ACCESS_DENIED', 'درخواست باید از یکی از واحدهای خودتان ثبت شود.'); const item: Request = { ...input, id: crypto.randomUUID(), title: input.title.trim(), description: input.description.trim(), createdBy: actor.userId, status: 'DRAFT', createdAt: new Date().toISOString() }; await this.requests.create(item); await this.audit(actor, 'REQUEST_CREATED', item); await this.activity.notify([actor.userId], { title: 'درخواست ایجاد شد', message: item.title, priority: 'NORMAL' }); return item }
  async submitRequest(actor: AuthorizedPrincipal, id: string) { const item = await this.require(id); this.assertOwner(actor, item); if (item.status !== 'DRAFT') throw new AppError('VALIDATION_ERROR', 'فقط درخواست پیش‌نویس قابل ارسال است.'); const updated = await this.requests.update({ ...item, status: 'SUBMITTED' }); await this.audit(actor, 'REQUEST_SUBMITTED', updated); await this.activity.notify(await this.managersFor(item.departmentId), { title: 'درخواست جدید', message: item.title, priority: item.priority }); return updated }
  async reviewRequest(actor: AuthorizedPrincipal, id: string) { const item = await this.managerRequest(actor, id, ['SUBMITTED']); const updated = await this.requests.update({ ...item, status: 'UNDER_REVIEW' }); await this.audit(actor, 'REQUEST_REVIEWED', updated); await this.activity.notify([item.createdBy], { title: 'بررسی درخواست آغاز شد', message: item.title, priority: 'NORMAL' }); return updated }
  async approveRequest(actor: AuthorizedPrincipal, id: string) { const item = await this.managerRequest(actor, id, ['SUBMITTED', 'UNDER_REVIEW']); const updated = await this.requests.update({ ...item, status: 'APPROVED' }); await this.finishAction(actor, 'REQUEST_APPROVED', updated, 'درخواست تأیید شد'); return updated }
  async rejectRequest(actor: AuthorizedPrincipal, id: string, reason: string) { if (!reason.trim()) throw new AppError('VALIDATION_ERROR', 'دلیل رد درخواست الزامی است.'); const item = await this.managerRequest(actor, id, ['SUBMITTED', 'UNDER_REVIEW']); const updated = await this.requests.update({ ...item, status: 'REJECTED', reviewReason: reason.trim() }); await this.finishAction(actor, 'REQUEST_REJECTED', updated, 'درخواست رد شد', reason); return updated }
  async escalateRequest(actor: AuthorizedPrincipal, id: string) { const item = await this.managerRequest(actor, id, ['SUBMITTED', 'UNDER_REVIEW']); const updated = await this.requests.update({ ...item, status: 'ESCALATED' }); await this.audit(actor, 'REQUEST_ESCALATED', updated); await this.activity.notify(await this.mainManagers(), { title: 'درخواست ارجاع‌شده', message: item.title, priority: item.priority }); await this.activity.notify([item.createdBy], { title: 'درخواست ارجاع شد', message: item.title, priority: 'NORMAL' }); return updated }
  async completeRequest(actor: AuthorizedPrincipal, id: string) { authorize(actor, Capabilities.REQUEST_REVIEW); const item = await this.require(id); const mainCompletingEscalated = actor.roles.includes('MAIN_MANAGER') && item.status === 'ESCALATED'; const managerCompletingApproved = actor.roles.includes('DEPARTMENT_MANAGER') && item.status === 'APPROVED' && isWithinScope(actor, { departmentId: item.departmentId }); if (!mainCompletingEscalated && !managerCompletingApproved) throw new AppError('PERMISSION_ERROR', 'تکمیل درخواست در این مرحله مجاز نیست.'); const updated = await this.requests.update({ ...item, status: 'COMPLETED' }); await this.finishAction(actor, 'REQUEST_COMPLETED', updated, 'درخواست تکمیل شد'); return updated }
  async getRequests(actor: AuthorizedPrincipal) { if (actor.roles.includes('MAIN_MANAGER')) { authorize(actor, Capabilities.REQUEST_REVIEW); return this.requests.findEscalated() } if (actor.roles.includes('DEPARTMENT_MANAGER')) { authorize(actor, Capabilities.REQUEST_REVIEW); return (await Promise.all(actor.departmentIds.map((id) => this.requests.findByDepartment(id)))).flat() } authorize(actor, Capabilities.REQUEST_CREATE); return this.requests.findByUser(actor.userId) }
  private async managerRequest(actor: AuthorizedPrincipal, id: string, statuses: readonly Request['status'][]) { authorize(actor, Capabilities.REQUEST_REVIEW); if (!actor.roles.includes('DEPARTMENT_MANAGER')) throw new AppError('PERMISSION_ERROR', 'بررسی اولیه فقط توسط مدیر واحد انجام می‌شود.'); const item = await this.require(id); if (!isWithinScope(actor, { departmentId: item.departmentId })) throw new AppError('ACCESS_DENIED', 'درخواست خارج از واحد شماست.'); if (!statuses.includes(item.status)) throw new AppError('VALIDATION_ERROR', 'وضعیت درخواست برای این عملیات مناسب نیست.'); return item }
  private validate(input: CreateRequestInput) { if (!input.departmentId || !input.title.trim() || !input.description.trim()) throw new AppError('VALIDATION_ERROR', 'عنوان، شرح و واحد درخواست الزامی است.') }
  private async isMember(userId: string, departmentId: string) { return (await this.memberships.findByUser(userId)).some((item) => item.departmentId === departmentId) }
  private assertOwner(actor: AuthorizedPrincipal, item: Request) { if (item.createdBy !== actor.userId) throw new AppError('ACCESS_DENIED', 'فقط ایجادکننده می‌تواند درخواست را ارسال کند.') }
  private async require(id: string) { const item = await this.requests.findById(id); if (!item) throw new AppError('NOT_FOUND', 'درخواست پیدا نشد.'); return item }
  private async audit(actor: AuthorizedPrincipal, action: string, after: Request) { await this.activity.record({ actorId: actor.userId, action, entityType: 'request', entityId: after.id, after }) }
  private async finishAction(actor: AuthorizedPrincipal, action: string, item: Request, title: string, message = item.title) { await this.audit(actor, action, item); await this.activity.notify([item.createdBy], { title, message, priority: 'NORMAL' }) }
}
