import { formatPersianDate, statusLabel } from '../../../core/utils'; import type { Approval, WorkflowHistoryRecord, WorkflowInstance } from '../types'
export const StatusBadge = ({ status }: { status: string }) => <span className={`badge badge--${status.toLowerCase()}`}>{statusLabel(status)}</span>
export const WorkflowTimeline = ({ workflow, history }: { workflow: WorkflowInstance; history: readonly WorkflowHistoryRecord[] }) => <section><StatusBadge status={workflow.currentStatus} /><ol className="timeline">{history.map((item) => <li key={item.id}><strong>{statusLabel(item.fromStatus)} ← {statusLabel(item.toStatus)}</strong><span>{item.changedBy}</span><time dateTime={item.createdAt}>{formatPersianDate(item.createdAt)}</time>{item.reason && <p>{item.reason}</p>}</li>)}</ol></section>
export const WorkflowHistory = WorkflowTimeline
export const ProgressTracker = ({ steps, current }: { steps: readonly string[]; current: string }) => <ol className="progress-tracker">{steps.map((step) => <li key={step} aria-current={step === current ? 'step' : undefined}><StatusBadge status={step} /></li>)}</ol>
export const ApprovalCard = ({ approval, onApprove, onReject }: { approval: Approval; onApprove?(id: string): void; onReject?(id: string): void }) => <article className="card"><header><strong>{approval.entityType}</strong><StatusBadge status={approval.status} /></header><span>تأییدکننده: {approval.approverId}</span>{approval.comment && <p>{approval.comment}</p>}{approval.status === 'PENDING' && <div className="button-row">{onApprove && <button type="button" onClick={() => onApprove(approval.id)}>تأیید</button>}{onReject && <button type="button" onClick={() => onReject(approval.id)}>رد</button>}</div>}</article>
export const ApprovalList = ({ approvals }: { approvals: readonly Approval[] }) => <div className="stack">{approvals.map((item) => <ApprovalCard key={item.id} approval={item} />)}</div>
export const ApprovalTimeline = ({ approvals }: { approvals: readonly Approval[] }) => <ol className="timeline">{approvals.map((item) => <li key={item.id}><StatusBadge status={item.status} /><time>{formatPersianDate(item.decidedAt ?? item.createdAt)}</time></li>)}</ol>
export const ApprovalModal = ({ approval, onClose }: { approval: Approval; onClose(): void }) => <div role="dialog" aria-modal="true" aria-label="بررسی تأیید"><ApprovalCard approval={approval} /><button type="button" onClick={onClose}>بستن</button></div>
