import {forwardRef,type ButtonHTMLAttributes,type ReactNode} from 'react';import {AppLink} from '../../app/navigation/AppLink';import type {IconName} from './Icon';import {Icon} from './Icon';import {cx} from './utils'
export type ButtonVariant='primary'|'secondary'|'outline'|'ghost'|'text'|'success'|'warning'|'danger';export type ButtonSize='sm'|'md'|'lg'
export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement>{variant?:ButtonVariant;size?:ButtonSize;loading?:boolean;fullWidth?:boolean;startIcon?:ReactNode;endIcon?:ReactNode;iconOnly?:boolean;rounded?:boolean;pressed?:boolean}
export const Button=forwardRef<HTMLButtonElement,ButtonProps>(function Button({variant='primary',size='md',loading=false,disabled,fullWidth=false,startIcon,endIcon,iconOnly=false,rounded=false,pressed,className,children,type='button',...props},ref){return <button ref={ref} type={type} className={cx('ui-button',`ui-button--${variant}`,`ui-button--${size}`,fullWidth&&'ui-button--full',iconOnly&&'ui-button--icon-only',rounded&&'ui-button--rounded',className)} disabled={disabled||loading} aria-busy={loading||undefined} aria-pressed={pressed} {...props}>{loading?<span className="ui-spinner ui-spinner--sm" aria-hidden="true"/>:startIcon}{!iconOnly&&<span>{children}</span>}{!loading&&endIcon}</button>})
export interface IconButtonProps extends Omit<ButtonProps,'children'|'iconOnly'|'aria-label'>{icon:IconName;label:string;tooltip?:string}
export const IconButton=forwardRef<HTMLButtonElement,IconButtonProps>(function IconButton({icon,label,tooltip=label,...props},ref){return <Button ref={ref} iconOnly aria-label={label} title={tooltip} startIcon={<Icon name={icon}/>} {...props}/>})
export interface FloatingActionButtonProps extends Omit<ButtonProps,'rounded'|'iconOnly'|'startIcon'>{icon:IconName;label:string;extended?:boolean;responsive?:boolean}
export const FloatingActionButton=forwardRef<HTMLButtonElement,FloatingActionButtonProps>(function FloatingActionButton({icon,label,extended=false,responsive=false,className,...props},ref){return <Button ref={ref} rounded iconOnly={!extended} startIcon={<Icon name={icon}/>} aria-label={label} className={cx('ui-fab',responsive&&'ui-fab--responsive',className)} {...props}>{label}</Button>})
export function ButtonGroup({children,orientation='horizontal',equal=false,segmented=false,responsive=false,className}:{children:ReactNode;orientation?:'horizontal'|'vertical';equal?:boolean;segmented?:boolean;responsive?:boolean;className?:string}){return <div className={cx('ui-button-group',`ui-button-group--${orientation}`,equal&&'ui-button-group--equal',segmented&&'ui-button-group--segmented',responsive&&'ui-button-group--responsive',className)} role={segmented?'group':undefined}>{children}</div>}
export function LinkButton({href,children,variant='primary',size='md',startIcon,endIcon,fullWidth=false,className}:{href:string;children:ReactNode;variant?:ButtonVariant;size?:ButtonSize;startIcon?:ReactNode;endIcon?:ReactNode;fullWidth?:boolean;className?:string}){return <AppLink href={href} className={cx('ui-button',`ui-button--${variant}`,`ui-button--${size}`,fullWidth&&'ui-button--full',className)}>{startIcon}<span>{children}</span>{endIcon}</AppLink>}
